import type { NodeDefinition } from './types';

export const triggerNodes: NodeDefinition[] = [
  {
    type: 'trigger_manual',
    category: 'trigger',
    name: 'Manual',
    icon: '▷',
    color: '#22c55e',
    description: 'Start workflow manually',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Start' }],
    defaultData: {},
    fields: [],
  },
  {
    type: 'trigger_hotkey',
    category: 'trigger',
    name: 'Hotkey',
    icon: '⌨️',
    color: '#22c55e',
    description: 'Trigger with keyboard shortcut',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Triggered' }],
    defaultData: { hotkey: '', enabled: true },
    fields: [
      { key: 'hotkey', label: 'Hotkey', type: 'hotkey', placeholder: 'Ctrl+Shift+A', required: true },
      { key: 'enabled', label: 'Enabled', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'trigger_schedule',
    category: 'trigger',
    name: 'Schedule',
    icon: '⏰',
    color: '#22c55e',
    description: 'Run on a schedule (cron)',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Trigger' }],
    defaultData: { cron: '0 * * * *', enabled: true },
    fields: [
      { key: 'cron', label: 'Cron Expression', type: 'cron', placeholder: '0 * * * * (every hour)', required: true },
      { key: 'enabled', label: 'Enabled', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'trigger_clipboard',
    category: 'trigger',
    name: 'Clipboard',
    icon: '📋',
    color: '#22c55e',
    description: 'Trigger on clipboard change',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Content' }],
    defaultData: { textOnly: true },
    fields: [
      { key: 'textOnly', label: 'Text Only', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'trigger_file_watch',
    category: 'trigger',
    name: 'File Watcher',
    icon: '👁️',
    color: '#22c55e',
    description: 'Trigger when file changes',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Changed' }],
    defaultData: { path: '', events: 'all' },
    fields: [
      { key: 'path', label: 'File/Folder Path', type: 'file', placeholder: '/path/to/watch', required: true },
      { key: 'events', label: 'Watch Events', type: 'select', options: [
        { value: 'all', label: 'All Changes' },
        { value: 'create', label: 'Created' },
        { value: 'modify', label: 'Modified' },
        { value: 'delete', label: 'Deleted' },
      ]},
    ],
  },
  {
    type: 'trigger_webhook',
    category: 'trigger',
    name: 'Webhook',
    icon: '🔗',
    color: '#22c55e',
    description: 'Trigger via HTTP webhook',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Request' }],
    defaultData: { method: 'POST', path: '/webhook' },
    fields: [
      { key: 'method', label: 'Method', type: 'select', options: [
        { value: 'GET', label: 'GET' },
        { value: 'POST', label: 'POST' },
        { value: 'PUT', label: 'PUT' },
      ]},
      { key: 'path', label: 'Path', type: 'text', placeholder: '/my-webhook' },
    ],
  },
  {
    type: 'trigger_startup',
    category: 'trigger',
    name: 'App Startup',
    icon: '🚀',
    color: '#22c55e',
    description: 'Run when app starts',
    inputs: [],
    outputs: [{ id: 'out', type: 'output', label: 'Start' }],
    defaultData: { delay: 0 },
    fields: [
      { key: 'delay', label: 'Delay (ms)', type: 'number', placeholder: '0', defaultValue: 0 },
    ],
  },
];
