// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendFile(arg1, arg2) {
  return window['go']['main']['ActionService']['AppendFile'](arg1, arg2);
}

export function Compress(arg1, arg2) {
  return window['go']['main']['ActionService']['Compress'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['ActionService']['CopyFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['ActionService']['DeleteFile'](arg1);
}

export function Extract(arg1, arg2) {
  return window['go']['main']['ActionService']['Extract'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['main']['ActionService']['FileExists'](arg1);
}

export function FileInfo(arg1) {
  return window['go']['main']['ActionService']['FileInfo'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['ActionService']['GenerateUUID']();
}

export function GetClipboard() {
  return window['go']['main']['ActionService']['GetClipboard']();
}

export function GetCurrentTime(arg1) {
  return window['go']['main']['ActionService']['GetCurrentTime'](arg1);
}

export function GetSecret(arg1) {
  return window['go']['main']['ActionService']['GetSecret'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['ActionService']['GetSetting'](arg1);
}

export function HTTPRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ActionService']['HTTPRequest'](arg1, arg2, arg3, arg4);
}

export function ListDirectory(arg1, arg2, arg3) {
  return window['go']['main']['ActionService']['ListDirectory'](arg1, arg2, arg3);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['ActionService']['MoveFile'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['ActionService']['OpenURL'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['ActionService']['ReadFile'](arg1);
}

export function RunCommand(arg1, arg2, arg3) {
  return window['go']['main']['ActionService']['RunCommand'](arg1, arg2, arg3);
}

export function SaveSecret(arg1, arg2) {
  return window['go']['main']['ActionService']['SaveSecret'](arg1, arg2);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['ActionService']['SaveSetting'](arg1, arg2);
}

export function SetClipboard(arg1) {
  return window['go']['main']['ActionService']['SetClipboard'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['ActionService']['ShowNotification'](arg1, arg2);
}

export function Sleep(arg1) {
  return window['go']['main']['ActionService']['Sleep'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['ActionService']['WriteFile'](arg1, arg2);
}
