// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadExcel(arg1, arg2) {
  return window['go']['main']['ExcelService']['ReadExcel'](arg1, arg2);
}

export function WriteExcel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ExcelService']['WriteExcel'](arg1, arg2, arg3, arg4);
}
