// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteExecution(arg1:string):Promise<void>;

export function DeleteFlow(arg1:string):Promise<void>;

export function ExportFlow(arg1:string):Promise<string>;

export function GetFlow(arg1:string):Promise<string>;

export function ImportFlow(arg1:string):Promise<string>;

export function Init():Promise<void>;

export function ListExecutions(arg1:number):Promise<Array<Record<string, any>>>;

export function ListFlows():Promise<Array<Record<string, any>>>;

export function LoadFlow(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function SaveExecution(arg1:string):Promise<void>;

export function SaveFlow(arg1:string):Promise<string>;

export function SaveSettings(arg1:string):Promise<void>;
