// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveTriggers() {
  return window['go']['main']['TriggerManager']['GetActiveTriggers']();
}

export function RegisterClipboardMonitor(arg1, arg2) {
  return window['go']['main']['TriggerManager']['RegisterClipboardMonitor'](arg1, arg2);
}

export function RegisterFileWatcher(arg1, arg2, arg3) {
  return window['go']['main']['TriggerManager']['RegisterFileWatcher'](arg1, arg2, arg3);
}

export function RegisterHotkey(arg1, arg2) {
  return window['go']['main']['TriggerManager']['RegisterHotkey'](arg1, arg2);
}

export function RegisterScheduleTrigger(arg1, arg2) {
  return window['go']['main']['TriggerManager']['RegisterScheduleTrigger'](arg1, arg2);
}

export function RegisterWebhookTrigger(arg1, arg2, arg3) {
  return window['go']['main']['TriggerManager']['RegisterWebhookTrigger'](arg1, arg2, arg3);
}

export function Shutdown() {
  return window['go']['main']['TriggerManager']['Shutdown']();
}

export function StartAllTriggers() {
  return window['go']['main']['TriggerManager']['StartAllTriggers']();
}

export function UnregisterClipboardMonitor() {
  return window['go']['main']['TriggerManager']['UnregisterClipboardMonitor']();
}

export function UnregisterFileWatcher(arg1) {
  return window['go']['main']['TriggerManager']['UnregisterFileWatcher'](arg1);
}

export function UnregisterHotkey(arg1) {
  return window['go']['main']['TriggerManager']['UnregisterHotkey'](arg1);
}

export function UnregisterScheduleTrigger(arg1) {
  return window['go']['main']['TriggerManager']['UnregisterScheduleTrigger'](arg1);
}

export function UnregisterWebhookTrigger(arg1, arg2, arg3) {
  return window['go']['main']['TriggerManager']['UnregisterWebhookTrigger'](arg1, arg2, arg3);
}
