// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveTriggers():Promise<Record<string, any>>;

export function RegisterClipboardMonitor(arg1:string,arg2:boolean):Promise<void>;

export function RegisterFileWatcher(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RegisterHotkey(arg1:string,arg2:string):Promise<void>;

export function RegisterScheduleTrigger(arg1:string,arg2:string):Promise<void>;

export function RegisterWebhookTrigger(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartAllTriggers():Promise<void>;

export function UnregisterClipboardMonitor():Promise<void>;

export function UnregisterFileWatcher(arg1:string):Promise<void>;

export function UnregisterHotkey(arg1:string):Promise<void>;

export function UnregisterScheduleTrigger(arg1:string):Promise<void>;

export function UnregisterWebhookTrigger(arg1:string,arg2:string,arg3:string):Promise<void>;
